name: Build
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - run: |
      
        gcc mi-thermal-crypt.c cmdline.c -o mi-thermal-crypt -lssl -lcrypto
        ls
        mkdir nonexistent_path
        mv *.c nonexistent_path
        mv mi* nonexistent_path
        mv cmd* nonexistent_path

    - uses: actions/upload-artifact@v3

      with:

        name: idk

        path: nonexistent_path
